[project]
name = "buildserver"
requires-python = ">=3.9"
version = "0.1.0"

dependencies = [
    "flask~=2.2.2",
    "python-dotenv~=1.0.0",
]

[project.optional-dependencies]
dev = [
    "black~=22.10.0",
    "pip-tools",
    "pytest~=7.2.0",
]
