[project]
name = "buildserver"
requires-python = ">=3.8"

dependencies = [
    "flask~=2.2.2",
]

[project.optional-dependencies]
dev = [
    "black~=22.10.0",
    "pip-tools",
    "pytest~=7.2.0",
]
